---
title: "Leaflet Exercise from Team PM3"
author: "Team PM2"
date: "16/04/2019"
output: html_document
---

#Task 0

```{r, include= FALSE}
library(leaflet)
library(dplyr)
library(readr)
library(countrycode)
library(rworldmap)
library(RColorBrewer)
```

```{r}
#setwd("DAVis/13A DAVIS/")
```

#Task 1

```{r}
data <- read.csv("CAIT Country CO2 Emissions.csv")
data$X.1[1]

data2014 <- read.csv("CAIT Country CO2 Emissions.csv", 
                     skip = 1, stringsAsFactors = FALSE) %>%
  rename(CO2 = 3) %>%
  filter(Year == 2014 & !(Country %in% c("European Union (28)", "World"))) %>%
  mutate(Country = gsub("Micronesia", 
                        "Federated State of Micronesia", Country),
         Code = countrycode(Country, "country.name", "iso3c"))


spdf <- joinCountryData2Map(data2014, nameJoinColumn = "Code")

spdf <- subset(spdf, continent != "Antarctica")
```


#Task 2

```{r}
leaflet(spdf) %>% addTiles() %>%
  setView(lng = 103.8198, lat = 1.3521, zoom = 12)# %>%
#addPolygons()
```

#Task 3

```{r}
breaks <- c(0, 10, 20, 50, 100, 200, 1000, 2000, 5000, 10000, 20000)
crp <- colorRampPalette(brewer.pal(9, "YlOrBr"))
pal <- colorBin(crp(length(breaks) - 1), domain = spdf$CO2, bins = breaks)

leaflet(spdf) %>% addTiles() %>%
  addPolygons(fillColor = ~pal(CO2), 
              color = "white", 
              dashArray = "3",
              weight = 2, fillOpacity = 0.8)
```

#Task 4

```{r}
leaflet(spdf) %>% addTiles() %>%
  addPolygons(fillColor = ~pal(CO2), 
              color = "white", 
              dashArray = "3",
              weight = 2, fillOpacity = 0.8, 
              highlight = highlightOptions(color = "black", 
                                           weight = 3, 
                                           opacity = 1,
                                           fillOpacity = 0.6,
                                           bringToFront = TRUE))
```

#Task 5

```{r}
label <- sprintf("<strong>%s</strong> <br/> CO<sub>2</sub> levels: %g", 
                 spdf$Country, spdf$CO2) %>%
  lapply(htmltools::HTML)
```


#Task 6
```{r}
leaflet(spdf) %>% addTiles() %>%
  addPolygons(fillColor = ~pal(CO2), 
              color = "white", 
              dashArray = "3",
              weight = 2, fillOpacity = 0.8, 
              highlight = highlightOptions(color = "black", 
                                           weight = 3, 
                                           opacity = 1,
                                           fillOpacity = 0.6,
                                           bringToFront = TRUE),
              label = label,
              labelOptions = labelOptions(direction = "auto",
                                          style = 
                                            list("font-wight" = "normal", 
                                                 padding = "3px 8px")))
```

#Task 7

```{r}
leaflet(spdf) %>% addTiles() %>%
  addPolygons(fillColor = ~pal(CO2), 
              color = "white", 
              dashArray = "3",
              weight = 2, fillOpacity = 0.8, 
              highlight = highlightOptions(color = "black", 
                                           weight = 3, 
                                           opacity = 1,
                                           fillOpacity = 0.6,
                                           bringToFront = TRUE),
              label = label,
              labelOptions = labelOptions(direction = "auto",
                                          style = 
                                            list("font-wight" = "normal", 
                                                 padding = "3px 8px"))) %>%
  addLegend(pal = pal, values = ~CO2, 
            title = "CO<sub>2</sub> emissions in Mt",
            opacity = 0.8,
            position = "bottomleft")

?addLegend
```

#Task 8
```{r}
library(htmltools)
library(htmlwidgets)

title <- tags$div(HTML("CO<sub>2</sub> Emissions around the Globe in 2014"))

leaflet(spdf) %>% addTiles() %>%
  addPolygons(fillColor = ~pal(CO2), 
              color = "white", 
              dashArray = "3",
              weight = 2, fillOpacity = 0.8, 
              highlight = highlightOptions(color = "black", 
                                           weight = 3, 
                                           opacity = 1,
                                           fillOpacity = 0.6,
                                           bringToFront = TRUE),
              label = label,
              labelOptions = labelOptions(direction = "auto",
                                          style = 
                                            list("font-wight" = "normal", 
                                                 padding = "3px 8px"))) %>% 
  addLegend(pal = pal, values = ~CO2, 
            title = "CO<sub>2</sub> emissions in Mt",
            opacity = 0.8,
            position = "bottomleft") %>%
  addControl(title, "topright")


```



#Task9

```{r}
library(htmltools)
library(htmlwidgets)

title <- tags$div(HTML("CO<sub>2</sub> Emissions around the Globe in 2014"))

leaflet(spdf) %>% addTiles() %>%
  addPolygons(fillColor = ~pal(CO2), 
              color = "white", 
              dashArray = "3",
              weight = 2, fillOpacity = 0.8, 
              highlight = highlightOptions(color = "black", 
                                           weight = 3, 
                                           opacity = 1,
                                           fillOpacity = 0.6,
                                           bringToFront = TRUE),
              label = label,
              labelOptions = labelOptions(direction = "auto",
                                          style = 
                                            list("font-wight" = "normal", 
                                                 padding = "3px 8px"))) %>% 
  addLegend(pal = pal, values = ~CO2, 
            title = "CO<sub>2</sub> emissions in Mt",
            opacity = 0.8,
            position = "bottomleft") %>%
  addControl(title, "topright")
```









